"""add tokens_used to message

Revision ID: 409baf6f2cd4
Revises: a28dfaf4b7a1
Create Date: 2023-03-03 22:27:13.765756

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '409baf6f2cd4'
down_revision = 'a28dfaf4b7a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('tokens_used', sa.Integer(), nullable=True))
    op.drop_column('user', 'tokens_used')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tokens_used', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('message', 'tokens_used')
    # ### end Alembic commands ###
