from random import choice

from lingua import Language


def random_english_placeholder() -> str:
    placeholders_en = [
        "Bear with...",
        "Still workin'...",
        "Not ready...",
        "Processing...",
        "Loading, loading...",
        "Standby mode...",
        "Percolating data...",
        "Almost there...",
        "Seeking answer...",
        "Brainstorming now...",
        "Page loading...",
        "Machine musing...",
        "Crickets chirping...",
        "Code crunching...",
        "Still computin'...",
        "Querying cosmos...",
        "Artificially pondering...",
        "Digitally decoding...",
        "Probing mind...",
        "Brain churning...",
        "Cogitating bytes...",
        "Analyzing Qs...",
        "Diligently deducing...",
        "Synthesizing thought...",
        "Information compiling...",
        "Virtual cogitation...",
        "Fact analyzing...",
        "Thinking thoughts...",
        "Processing universe...",
        "Awaiting algorithms...",
        "AI ruminating...",
        "Evaluating data...",
        "Computer cogitating...",
        "Bytes processing...",
        "In processing...",
        "Machine learning...",
        "Artificial thinking...",
        "Digital deliberation...",
        "Computation commencing...",
        "Bits and pieces...",
        "Working wheels...",
        "Decoding responses...",
        "Data mining...",
        "Analyzing bits...",
        "Forecasting answers...",
        "In computing...",
        "Quantum computing...",
        "Data dialectics...",
        "Mining for gold...",
        "Algorithms computing...",
        "Collecting thoughts...",
        "Computing strings...",
        "Quantum thinking...",
        "Data processing...",
        "Bytes and pieces...",
        "Calculating results...",
        "Infiltrating data...",
        "Digging for data...",
        "Powering up...",
    ]

    return choice(seq=placeholders_en)


def random_russian_placeholder() -> str:
    placeholders_ru = [
        "Анализируем вопрос...",
        "В процессе...",
        "Взбираем знания...",
        "Вычисляем ответ...",
        "Генерируем новые идеи...",
        "Делаем расчеты...",
        "Думаем дальше...",
        "Жарим мысли...",
        "Ждем-с...",
        "Ждите-с...",
        "Железо теребим...",
        "Жуём байты...",
        "Загружаем...",
        "Загружаемся...",
        "Исследуем данные...",
        "Исследуем детальнее...",
        "Ищем ответ...",
        "Качаем процессор...",
        "Компьютер готовится...",
        "Компьютерная подготовка...",
        "Компьютим...",
        "Машина думает...",
        "Мозгатое дело...",
        "Мониторим состояние...",
        "Мыслительный процесс...",
        "Немного потерпите...",
        "О, скоро...",
        "Обрабатываем...",
        "Общаемся с облаками...",
        "Ожидайте-с...",
        "Ожидание...",
        "Перекипание данных...",
        "Перерабатываю...",
        "Подгоняем данные...",
        "Подготовка...",
        "Подсчёт результатов...",
        "Проверяем ответы...",
        "Работаем-работаем...",
        "Работаем...",
        "Разбираем ответы на кусочки...",
        "Размышляем...",
        "Ручаемся за точность...",
        "Сканируем результаты...",
        "Суммируем данные...",
        "Трансформируем ответы...",
        "Угадаем ваш вопрос...",
        "Углубляемся...",
        "Числа-буквы...",
        "Читаем между строк...",
        "Экстраполяция данных...",
    ]

    return choice(seq=placeholders_ru)


def get_placeholder(*, language: Language | None) -> str:
    if language == Language.RUSSIAN:
        return random_russian_placeholder()

    return random_english_placeholder()
